deploy-master:
  stage: deploy
  environment:
    name: master
    url: http://oez.ksdev.ru
  variables:
    DEPLOY_PATH : "~/oez.ksdev.ru/master/"
    GIT_STRATEGY: none
  script:
  - echo "Deploy master"
  - echo $DEPLOY_PATH
  - ssh -T ksdev "cd $DEPLOY_PATH && git pull && /opt/plesk/php/7.1/bin/php composer.phar install -n --no-dev"
  only:
  - master

deploy-dev:
  stage: deploy
  environment:
    name: dev
    url: http://oez-d.ksdev.ru
  variables:
    DEPLOY_PATH : "~/oez.ksdev.ru/dev/"
    GIT_STRATEGY: none
  script:
  - echo "Deploy dev"
  - echo $DEPLOY_PATH
  - ssh -T ksdev "cd $DEPLOY_PATH && git pull && /opt/plesk/php/7.1/bin/php composer.phar install -n"
  only:
  - dev

deploy-test:
  stage: deploy
  environment:
    name: test
    url: http://oez-t.ksdev.ru
  variables:
    DEPLOY_PATH : "~/oez.ksdev.ru/test/"
    GIT_STRATEGY: none
  script:
  - echo "Deploy test"
  - echo $DEPLOY_PATH
  - ssh -T ksdev "cd $DEPLOY_PATH && git pull && /opt/plesk/php/7.1/bin/php composer.phar install -n --no-dev"
  only:
  - test
