deploy-master:
  stage: deploy
  environment:
    name: master
    url: http://www.spbsez.ru
  variables:
    DEPLOY_PATH : "~/ext_www/spbsez.ru/"
    GIT_STRATEGY: none
  script:
  - echo "Deploy master"
  - echo $DEPLOY_PATH
  - ssh -T oez "cd $DEPLOY_PATH && git pull && php composer.phar install -n --no-dev --no-progress"
  only:
  - master

deploy-dev:
  stage: deploy
  environment:
    name: dev
    url: http://oez-d.ksdev.ru
  variables:
    DEPLOY_PATH : "/var/www/oez-d.ksdev.ru/web/"
    GIT_STRATEGY: none
    BECOME_USER: "sudo -u `stat -c %U ../web`"
  script:
  - echo "Deploy dev"
  - echo $DEPLOY_PATH
  - ssh -T dev.ksdev.ru "cd $DEPLOY_PATH && $BECOME_USER git remote set-url origin $CI_REPOSITORY_URL && $BECOME_USER git pull && $BECOME_USER php7.1 composer.phar install -n --no-progress"
  only:
  - dev

deploy-test:
  stage: deploy
  environment:
    name: test
    url: http://oez-t.ksdev.ru
  variables:
    DEPLOY_PATH : "/var/www/oez-t.ksdev.ru/web/"
    GIT_STRATEGY: none
    BECOME_USER: "sudo -u `stat -c %U ../web`"
  script:
  - echo "Deploy test"
  - echo $DEPLOY_PATH
  - ssh -T dev.ksdev.ru "cd $DEPLOY_PATH && $BECOME_USER git remote set-url origin $CI_REPOSITORY_URL && $BECOME_USER git pull && $BECOME_USER php7.1 composer.phar install -n --no-dev --no-progress"
  only:
  - test
