version: '3.4'

x-volumes:
  - &project .:/var/www/
  - &ssh ~/.ssh/:/root/.ssh/:ro

services:
  web:
    container_name: oez_web
    image: docker.ksdev.ru/php/php-apache:7.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - *project
      - *ssh
    restart: always
    user: developer:developer
    working_dir: /var/www

  node:
    container_name: amgrad_node
    image: docker.ksdev.ru/nodejs/node:10
    ports:
      - 8080:8080
      - 3000:3000
      - 3001:3001
    volumes:
      - *project
      - *ssh
    user: node:node
    command: nodejs /home/node/http_server.js
    working_dir: /var/www
