CREATE TABLE IF NOT EXISTS `kelnik_userdata_contact` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `POSITION` varchar(255) DEFAULT NULL,
  `FIO` varchar(255) DEFAULT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`),
  KEY `DATE_MODIFIED` (`DATE_MODIFIED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kelnik_userdata_docs` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `FILE_ID` int(11) unsigned DEFAULT '0',
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`),
  KEY `DATE_MODIFIED` (`DATE_MODIFIED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
