DROP TABLE IF EXISTS `kelnik_vacancy`;
CREATE TABLE IF NOT EXISTS `kelnik_vacancy` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SORT` INT(11) NOT NULL DEFAULT '500',
  `PRICE_MIN` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `PRICE_MAX` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ACTIVE` ENUM('Y','N') NOT NULL DEFAULT 'N',
  `NAME` VARCHAR(255) NOT NULL,
  `PRICE_TEXT` VARCHAR(255) NULL DEFAULT NULL,
  `EXPERIENCE` VARCHAR(255) NULL DEFAULT NULL,
  `EMPLOYMENT` VARCHAR(255) NULL DEFAULT NULL,
  `DESCR_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
  `DUTIES_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
  `REQUIREMENTS_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
  `CONDITIONS_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
  `DESCR` TEXT NULL,
  `DUTIES` TEXT NULL,
  `REQUIREMENTS` TEXT NULL,
  `CONDITIONS` TEXT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `kelnik_vacancy_response`;
CREATE TABLE IF NOT EXISTS `kelnik_vacancy_response` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `VACANCY_ID` INT(11) UNSIGNED NULL DEFAULT '0',
  `FILE_ID` INT(11) UNSIGNED NULL DEFAULT '0',
  `DATE_CREATED` DATETIME NOT NULL,
  `USER_HASH` VARCHAR(32) NULL DEFAULT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(50) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `VACANCY_ID` (`VACANCY_ID`),
  INDEX `DATE_CREATED` (`DATE_CREATED`),
  INDEX `USER_HASH` (`USER_HASH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `kelnik_vacancy_residents`;
CREATE TABLE IF NOT EXISTS `kelnik_vacancy_residents` (
    `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `SORT` INT(11) NOT NULL DEFAULT '500',
    `PRICE_MIN` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    `PRICE_MAX` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    `ACTIVE` ENUM('Y','N') NOT NULL DEFAULT 'N',
    `NAME` VARCHAR(255) NOT NULL,
    `RESIDENT_ID` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    `PRICE_TEXT` VARCHAR(255) NULL DEFAULT NULL,
    `EXPERIENCE` VARCHAR(255) NULL DEFAULT NULL,
    `EMPLOYMENT` VARCHAR(255) NULL DEFAULT NULL,
    `CONTACTS` VARCHAR(255) NULL DEFAULT NULL,
    `DESCR_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
    `DUTIES_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
    `REQUIREMENTS_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
    `CONDITIONS_TEXT_TYPE` VARCHAR(4) NULL DEFAULT 'html',
    `DESCR` TEXT NULL,
    `DUTIES` TEXT NULL,
    `REQUIREMENTS` TEXT NULL,
    `CONDITIONS` TEXT NULL,
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
