CREATE TABLE IF NOT EXISTS `kelnik_report_status` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SORT` int(11) DEFAULT '500',
  `ACTIVE` enum('Y','N') DEFAULT 'N',
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SORT` (`SORT`),
  KEY `ACTIVE` (`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
