DROP TABLE IF EXISTS `sportsoft_banner`;
CREATE TABLE IF NOT EXISTS `sportsoft_banner` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ACTIVE` ENUM('Y','N') NOT NULL DEFAULT 'N',
  `NAME` VARCHAR(255) NOT NULL,
  `NAME_EN` VARCHAR(255),
  `SUBTITLE` VARCHAR(255),
  `SUBTITLE_EN` VARCHAR(255),
  `LINK` VARCHAR(255),
  `POSITION_ID` INT(11) NOT NULL,
  `IMAGE` VARCHAR(255),
  `OVERLAY` VARCHAR(255),
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `POSITION` (`POSITION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `sportsoft_banner_position`;
CREATE TABLE IF NOT EXISTS `sportsoft_banner_position` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ACTIVE` ENUM('Y','N') NOT NULL DEFAULT 'N',
  `NAME` VARCHAR(255) NOT NULL,
  `CODE` VARCHAR(255) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;