CREATE TABLE IF NOT EXISTS `kelnik_request` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `TYPE_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `STATUS_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `CODE` varchar(50) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `BODY` text,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `TYPE_ID` (`TYPE_ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`),
  KEY `DATE_MODIFIED` (`DATE_MODIFIED`),
  KEY `STATUS_ID` (`STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kelnik_request_areas` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SORT` int(11) DEFAULT '500',
  `ACTIVE` enum('Y','N') DEFAULT 'N',
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SORT` (`SORT`),
  KEY `ACTIVE` (`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_notify` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `IS_NEW` enum('Y','N') NOT NULL DEFAULT 'Y',
  `NAME` varchar(255) DEFAULT NULL,
  `TEXT` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IS_NEW` (`IS_NEW`),
  KEY `USER_ID` (`USER_ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_service` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE_ID` int(3) unsigned NOT NULL DEFAULT '0',
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `USER_HASH` varchar(32) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `COMPANY` varchar(255) DEFAULT NULL,
  `POSITION` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(150) DEFAULT NULL,
  `PHONE` varchar(50) DEFAULT NULL,
  `BODY` text,
  PRIMARY KEY (`ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`),
  KEY `DATE_MODIFIED` (`DATE_MODIFIED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_site` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `USER_HASH` varchar(32) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(150) DEFAULT NULL,
  `PHONE` varchar(50) DEFAULT NULL,
  `BODY` text,
  PRIMARY KEY (`ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`),
  KEY `DATE_MODIFIED` (`DATE_MODIFIED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_statuses` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SORT` int(11) DEFAULT '500',
  `ACTIVE` enum('Y','N') DEFAULT 'N',
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SORT` (`SORT`),
  KEY `ACTIVE` (`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_types` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SORT` int(11) DEFAULT '500',
  `ACTIVE` enum('Y','N') DEFAULT 'N',
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SORT` (`SORT`),
  KEY `ACTIVE` (`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_permit` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `TYPE_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `STATUS_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `DATE_START` datetime NOT NULL,
  `DATE_FINISH` datetime NOT NULL,
  `CODE` varchar(50) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `TARGET` varchar(255) DEFAULT NULL,
  `EXECUTIVE_COMPANY` varchar(255) DEFAULT NULL,
  `EXECUTIVE_VISIT` varchar(255) DEFAULT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `TYPE_ID` (`TYPE_ID`),
  KEY `DATE_CREATED` (`DATE_CREATED`),
  KEY `DATE_MODIFIED` (`DATE_MODIFIED`),
  KEY `STATUS_ID` (`STATUS_ID`),
  KEY `DATE_START` (`DATE_START`),
  KEY `DATE_FINISH` (`DATE_FINISH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
