CREATE TABLE IF NOT EXISTS `kelnik_request` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `TYPE_ID` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `STATUS_ID` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `DATE_CREATED` DATETIME NOT NULL,
  `DATE_MODIFIED` DATETIME NOT NULL,
  `CODE` VARCHAR(50) NULL DEFAULT NULL,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `BODY` TEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `USER_ID` (`USER_ID`),
  INDEX `TYPE_ID` (`TYPE_ID`),
  INDEX `DATE_CREATED` (`DATE_CREATED`),
  INDEX `DATE_MODIFIED` (`DATE_MODIFIED`),
  INDEX `STATUS_ID` (`STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kelnik_request_site` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`DATE_CREATED` DATETIME NOT NULL,
	`DATE_MODIFIED` DATETIME NOT NULL,
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`EMAIL` VARCHAR(150) NULL DEFAULT NULL,
	`PHONE` VARCHAR(50) NULL DEFAULT NULL,
	`BODY` TEXT NULL,
	PRIMARY KEY (`ID`),
	INDEX `DATE_CREATED` (`DATE_CREATED`),
	INDEX `DATE_MODIFIED` (`DATE_MODIFIED`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `kelnik_request_statuses` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SORT` int(11) DEFAULT '500',
  `ACTIVE` enum('Y','N') DEFAULT 'Y',
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SORT` (`SORT`),
  KEY `ACTIVE` (`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_types` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SORT` int(11) DEFAULT '500',
  `ACTIVE` enum('Y','N') DEFAULT 'N',
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SORT` (`SORT`),
  KEY `ACTIVE` (`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `kelnik_request_notify` (
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`DATE_CREATED` DATETIME NOT NULL,
	`DATE_MODIFIED` DATETIME NOT NULL,
	`IS_NEW` ENUM('Y','N') NOT NULL DEFAULT 'Y',
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`TEXT` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `IS_NEW` (`IS_NEW`),
	INDEX `USER_ID` (`USER_ID`),
	INDEX `DATE_CREATED` (`DATE_CREATED`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB ROW_FORMAT=COMPACT;

